# Use the official Python image from the Docker Hub
FROM public.ecr.aws/lambda/python:3.13

# Copy requirements.txt
COPY requirements_web_server.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Copy shared code and function code
COPY config.py fantasy_api.py s3_operation.py utils.py ${LAMBDA_TASK_ROOT}/
COPY web_server.py yahoo_oauth.py ${LAMBDA_TASK_ROOT}/

# Command to run the Lambda function
CMD ["web_server.lambda_handler"]
