# Use the official Python image from the Docker Hub
FROM public.ecr.aws/lambda/python:3.11


# Copy shared code
COPY config.py fantasy_api.py s3_operation.py utils.py ${LAMBDA_TASK_ROOT}/

# Copy requirements.txt
COPY requirements_web_server.txt ${LAMBDA_TASK_ROOT}/requirements.txt

# Install the specified packages
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Copy function code
COPY web_server.py yahoo_oauth.py ${LAMBDA_TASK_ROOT}/

# List the contents of the Lambda task root after copying function code
RUN ls -l ${LAMBDA_TASK_ROOT}


# Command to run the Lambda function
CMD ["web_server.lambda_handler"]
